/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on 28 Jan, 2013, 11:13:09 AM
 */

package com.navkar.faltu;

import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.ArrayList;
import java.util.Arrays;
import java.awt.Desktop;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.JTextField;
import java.util.Calendar;
 import java.io.BufferedReader;
import java.io.FileReader;
import java.io.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.*;
/**
 *
 * @author Pram
 */
public class MainForm extends javax.swing.JFrame {
    public String inputFile =  null;
    public String outputFile=null;
HashMap<Object, Integer> ht = new HashMap<Object, Integer>();
    //int upper = getParamAsInteger(jTextField2);
    //int lower = getParamAsInteger(jTextField3);
    //public int upper=Integer.parseInt(jTextField3.getText());
    //public int lower=Integer.parseInt(jTextField4.getText());

    /** Creates new form MainForm */
    public MainForm() {
      
        initComponents();
    } 
        
        
        
        
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Choose Input File:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Open File...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Minimum Support:");

        jLabel5.setText("Maximum Support:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Run Algorithm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(15);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 204, 204));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(30);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleParent(jPanel1);

        jLabel6.setText("Task Name :");

        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 153, 204));
        jTextArea2.setRows(30);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("LARGE ITEMSETS");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("PRE-LARGE ITEMSETS");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton4.setText("CLEAR ALL TEXT FIELDS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 102, 102));
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Statistics:");

        jButton2.setText("View Previous Result");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Output on Desktop");

        jLabel1.setText("Confidence");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel7)
                        .addGap(180, 180, 180)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addGap(352, 352, 352))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(82, 82, 82)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(jTextField4))))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(jLabel5)))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5))
                                .addGap(31, 31, 31)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("RETAIL MINING ");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("MINING WORKING FORM");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                         File path=null;
                      
        final JFileChooser fc = new JFileChooser(path);
		        	fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
					int returnVal = fc.showOpenDialog(MainForm.this);
			        if (returnVal == JFileChooser.APPROVE_OPTION) {
			            File file = fc.getSelectedFile();
                                    //TAKE INPUT FILE
			            jTextField1.setText(file.getPath());
			            inputFile=file.getPath();
                                    
			        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

/*
    public class StatusWindow extends Applet{
          public void init()
          {
              setBackground(Color.cyan);
          }
      public void paint(Graphics g)
      {
          g.drawString("This is in the applet window.", 10, 20);
          showStatus("This is shown in the status window."); }
}*/
// Display msg in applet window. public void paint(Graphics g) { g.drawString("This is in the applet window.", 10, 20); showStatus("This is shown in the status window."); }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

//      jProgressBar1.setStringPainted(true);
   
    /*  int n=0;
      while(n!=100)
      {*/
        int cnt=0;
      BufferedReader br = null;
       String instr=new String(inputFile);
        //-----------------------------------
       
try {
			String sCurrentLine;
			br = new BufferedReader(new FileReader(instr));


                        //NO OF RECORDS IN 'input' FILE
			while ((sCurrentLine = br.readLine()) != null)
			{	cnt++;
                             
			}//System.out.println("No of transactions:"+ cnt);
               

                
                //----------------Function to safety bound
               
                //----------------
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
					try {
							if (br != null)br.close();
						}
				 	catch (IOException ex) {
							ex.printStackTrace();
						}
		}



   outputFile=jTextField2.getText();
     
      String outstr=new String(outputFile );
      int b=0;
      int x= Integer.parseInt( jTextField3.getText());
      int y=Integer.parseInt( jTextField4.getText());
      int conf=Integer.parseInt(jTextField5.getText());
        //-----------------------------------
        ArrayList<String> fname=new ArrayList<String>();
                           
                
                try {

                    FileInputStream fis = new FileInputStream("alltask.txt");
                    ObjectInputStream ois = new ObjectInputStream(fis);
                    fname = (ArrayList<String>) ois.readObject();
                    
                    ois.close();
                    }
                catch (Exception e) {
                    System.out.println("Exception during deserialization: " + e);
                    System.exit(0);
                    }
                    
                    String str=new String();
                    ListIterator itr = fname.listIterator();
                   int h=0;
                   while(itr.hasNext()) {
                    str =(String) itr.next();
                    if(jTextField2.getText().equals(str))
                    {
                      String xyz=str;
                    }
                    h++;
                   }
                    if(jTextField2.getText().equals(str))
                    {
                          
                         
                         JOptionPane.showMessageDialog(null,"You are applying incremental mining for this dataset as safety bound increases.....","Correct Login",JOptionPane.OK_OPTION);
                         Incmining s=new Incmining(instr,outstr,y,x,conf);
       //n=System.currentTimeMillis();
       

                     }
                    else{
          //FEB s=new FEB(instr,outstr,y,x);
         // NewMain s=new NewMain(instr,outstr,y,x);
         //test s=new test(instr,outstr,y,x);
                         mining1 s=new mining1(instr,outstr,y,x,conf);
                        }
                        
                        
                        
                        
                    
                    
                    
                  // jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(str));
       
        
    
//--------------
       
   


        
///////////////////////////////////////////////////////////////////////////////////////////
       //	ArrayList<Set<List<Integer>>> n_k = new ArrayList<Set<List<Integer>>>();//Large sequence
        //ArrayList<Set<List<Integer>>> p_k = new ArrayList<Set<List<Integer>>>();// pre Large sequence
       
        ArrayList<Set<List<String>>> n_k = new ArrayList<Set<List<String>>>();//Large sequence
        ArrayList<Set<List<String>>> p_k = new ArrayList<Set<List<String>>>();
        
        int cntpre=0;
        int cntlarge=0;
        //long temps=0;
try {

FileInputStream fis = new FileInputStream(outputFile);
ObjectInputStream ois = new ObjectInputStream(fis);
//n_k = (ArrayList<Set<List<Integer>>>)ois.readObject();
//p_k = (ArrayList<Set<List<Integer>>>)ois.readObject();

n_k = (ArrayList<Set<List<String>>>)ois.readObject();
p_k = (ArrayList<Set<List<String>>>)ois.readObject();
cntpre=fis.read();
//temps=ois.read();

ois.close();
}
catch(Exception e) {
System.out.println("Exception during deserialization: " + e);
System.exit(0);
}


try{
            FileInputStream fis = new FileInputStream(outputFile+"hash");
            ObjectInputStream ois = new ObjectInputStream(fis);
            ht = (HashMap) ois.readObject();
}
catch(Exception e) {
System.out.println("Exception during deserialization: " + e);
System.exit(0);
}
		//Print everything in n_k
          //       jTextArea1.append("\n@=======ALGORITHM STATISTICS=========\n");
               //  jTextArea1.append("\nNo of large itemsets: " +cntlarge+"");
//                 jTextArea1.append("\nNo of Pre-large itemsets: " +temps+"");
                 jTextArea1.append("\n@=====================================\n\n");
		 jTextArea1.append("\n Done calculating frequent LARGE itemsets\n");
                  jTextArea1.append("\n@=====================================\n");
		for(Set<List<String>> set : n_k){
			//Each level
                    String ss=new String();
                    jTextArea1.append("\n new level\n");
                   // System.out.println("New Level");
			for(List<String> list : set){
                            //System.out.println("\nSet: "+ ss.valueOf(list));
				 jTextArea1.append("\nSet: " + ss.valueOf(list));
                         //--------------------------------
       String[][] db=new String[1000][];
        String [] arr;
        String x1=ss.valueOf(list);
        String y1=x1.replace("[","" );
        String z=y1.replace("]","" );
        //System.out.println(z);
        arr=z.split("[:,:]");
        //System.out.println(arr);
      String status=null;
       int ct=0;
       int k=0;
       jTextArea1.append("[");
        for(int i=0;i<arr.length;i++)
        {               
        //arr[i].trim();
        String dataSourceName = "mining";
        String dbURL = "jdbc:odbc:" + dataSourceName;
        try { 
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con = DriverManager.getConnection(dbURL, "","");
        
        Statement st=con.createStatement();
        ResultSet rs = st.executeQuery("select * from ProductMaster where Key='"+arr[i].trim()+"' ");
        
         if(rs.next()){
               jTextArea1.append(""+ rs.getString(2)+",");
                //status=status+","+rs.getString(2);
             
               
             
             
           }
         
         
         

        rs.close();
        st.close();
        con.close();
        
       }
       catch (Exception err) {
        System.out.println( "Error: " + err );
      }
     }
        
       
       // System.out.println(db[k]);
         k++;
			}
		}

////////////////preeeeeeeeeeeee////////////////////////////////////////////////////////////////////////

		//Print everything in p_k
              //  jTextArea2.append("\n@========ALGORITHM STATISTICS========\n");
               jTextArea2.append("\nNo of Pre-large itemsets:" +cntpre+"");
               jTextArea2.append("\n@===================================\n\n");
	       jTextArea2.append("\nDone calculating frequent PRE-LARGE itemsets\n");
	       for(Set<List<String>> set : p_k){
			//Each level
                   String ss=new String();
                    jTextArea2.append("\n new level\n");
                    //System.out.println("New Level");
			for(List<String> list : set){
				 jTextArea2.append("\nSet: " + ss.valueOf(list));

                                 //---------
                                 String[][] db=new String[1000][];
                                 String [] arr1;
                                 String x12=ss.valueOf(list);
                                 String y12=x12.replace("[","" );
                                 String z2=y12.replace("]","" );
                                // System.out.println(z2);
                                 arr1=z2.split("[:,:]");
                                 //System.out.println(arr1);
                                 
                                 jTextArea2.append("[");
                                 for(int j=0;j<arr1.length;j++)
                                 {
                                      String dataSourceName = "mining";
        String dbURL = "jdbc:odbc:" + dataSourceName;
        try { 
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con = DriverManager.getConnection(dbURL, "","");
        
        Statement st=con.createStatement();
        ResultSet rs = st.executeQuery("select * from ProductMaster where Key='"+arr1[j].trim()+"' ");
        
         if(rs.next()){
             
               jTextArea2.append(""+ rs.getString(2)+",");
                //status=status+","+rs.getString(2);
               
               
             //System.out.println(rs.getString(2));
             
           }
         
     
        rs.close();
        st.close();
        con.close();
        
       }
       catch (Exception err) {
        System.out.println( "Error: " + err );
      }
                                 }
                                 jTextArea2.append("]");
                                 //---------

			}
		}
        

////////////////////////////////////////////////////////////////////////////////////////



        if(jCheckBox1.isSelected()){
					Desktop desktop = Desktop.getDesktop();
				  if (desktop.isSupported(Desktop.Action.OPEN)) {
					  try{
					  desktop.open(new File(outputFile+"LARGE.txt"));
                                          desktop.open(new File(outputFile+"PRELARGE.txt"));
					  }catch(IOException e){
						  JOptionPane.showMessageDialog(null,
								    "The output file failed to open with the default application. " +
								    "\n This error occurs if there is no default application on your system " +
								    "for opening the output file or the application failed to start. " +
								    "\n\n" +
								    "To fix the problem, consider changing the extension of the output file to .txt." +
								    "\n\n ERROR MESSAGE = " + e.toString(), "Error",
								    JOptionPane.ERROR_MESSAGE);
					  }catch(SecurityException e){
						  JOptionPane.showMessageDialog(null,
								    "A security error occured while trying to open the output file. ERROR MESSAGE = " + e.toString(), "Error",
								    JOptionPane.ERROR_MESSAGE);
                                                  
					  }catch(Exception e){
						  JOptionPane.showMessageDialog(null,
								    "An error occured while opening the output file. ERROR MESSAGE = " + e.toString(), "Error",
								    JOptionPane.ERROR_MESSAGE);
					  }
				  }
				}
    }//GEN-LAST:event_jButton3ActionPerformed
 private int countforconfidence(Integer db) {
		BufferedReader br = null;
              int count=0;
		try {

			String sCurrentLine;

			br = new BufferedReader(new FileReader(inputFile));
 			String[] arr1 = null;
 			
 			int k=0;
 			

			while ((sCurrentLine = br.readLine()) != null)
			{
				arr1 = sCurrentLine.split(",");
				
				
				for(int i = 0; i < arr1.length; i++)
				{
					if(Integer.parseInt( arr1[i])==db)
                                        {
                                            count++;
                                        }

				}

					k++;
			}

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				if (br != null)br.close();
			} catch (IOException ex) {
				ex.printStackTrace();
			}
		}
		return count;
	}   
       
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 jTextField1.setText("");
 jTextField2.setText("");
 jTextField3.setText("");
 jTextField4.setText("");
 jTextArea1.setText("");
 jTextArea2.setText("");
 jButton3.getDisabledSelectedIcon();// TODO add your handling code here:

 this.dispose();
 MainForm mm=new MainForm();

 mm.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
Result re=new Result();
re.setVisible(true);
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AdministratorForm af=new AdministratorForm();
        af.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
                
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    protected javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    protected static javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    protected static javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
